prompts = [
    "best breakfast food",
    "something you bring to school",
    "zoo animal",
    "pet animal",
    "best disney movie",
    "superpower you want",
    "most addictive food",
    "best fast food chain",
    "something embarrassing to do",
    "something people lose often",
    "best pizza topping",
    "worst chore",
    "something you do before sleeping",
    "popular sport",
    "something cold",
    "something hot",
    "thing you do when bored",
    "best ice cream flavor",
    "something found in a backpack",
    "something people are afraid of",
    "thing people do on their phone",
    "best subject in school",
    "worst subject in school",
    "popular app",
    "something you can’t live without",
    "something at the beach",
    "thing people forget",
    "best holiday",
    "something you wear",
    "popular candy",
    "something red",
    "something blue",
    "popular video game",
    "popular movie snack",
    "thing people hate waiting for",
    "something sticky",
    "something fluffy",
    "something expensive",
    "something cheap",
    "best smell",
    "worst smell",
    "something in a kitchen",
    "something in a classroom",
    "thing people do in the morning",
    "something noisy",
    "something quiet",
    "best weather",
    "something you would find in a car",
    "popular drink",
    "something people do at a party",
    "something round",
    "something square",
    "thing people forget to charge",
    "something people collect",
    "best fruit",
    "worst tasting vegetable",
    "something people procrastinate",
    "popular YouTuber",
    "popular singer",
    "something that flies",
    "something underwater",
    "something you should not lick",
    "something kids say",
    "something teachers say",
    "something parents say",
    "something people do while procrastinating",
    "something you can smell from far away",
    "something people fake",
    "something people complain about",
    "best chip flavor",
    "something in a refrigerator",
    "something you would see at a carnival",
    "best thing about weekends",
    "something people do during class",
    "something awkward",
    "thing people do when nervous",
    "something everyone has touched",
    "something soft",
    "something sharp",
    "best school lunch",
    "worst school lunch",
    "something you shouldn’t say to a teacher",
    "something you shouldn’t do at a wedding",
    "thing people do in elevators",
    "something you can throw",
    "something breakable",
    "something people waste money on",
    "best cereal",
    "something people trip over",
    "thing people Google",
    "something in a teenager’s room",
    "best road trip snack",
    "something people forget in hotels",
    "something you should never microwave",
    "something people do at the gym",
    "something annoying",
    "best smartphone app",
    "thing people lie about",
    "thing people do when nobody is watching",
    "something people do too much",
    "something people pretend to understand",
    "something difficult to spell",
    "something people always misplace",
    "thing people do in traffic",
    "something people post online",
    "something that smells bad but tastes good"
]